apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubefirst-console
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubefirst.github.io/charts
    targetRevision: 2.0.0
    chart: console
    helm:
      values: |-
        env:
          ADMIN_EMAIL:
            value: ""
          CLUSTER_NAME:
            value: "kubefirst"
          HOSTED_ZONE_NAME:
            value: ""
          GITHUB_HOST:
            value: "github.com"
          GITHUB_OWNER:
            value: "rcompos"
          ARGO_WORKFLOWS_URL:
            value: "http://localhost:2746"
          VAULT_URL:
            value: "http://localhost:8200"
          ARGO_CD_URL:
            value: "http://localhost:8080"
          ATLANTIS_URL:
            value: "http://localhost:4141"
          METAPHOR_DEV:
            value: "http://localhost:3000"
          METAPHOR_GO_DEV:
            value: "http://localhost:5000"
          METAPHOR_FRONT_DEV:
            value: "http://localhost:4000"
          METAPHOR_STAGING:
            value: "http://localhost:3001"
          METAPHOR_GO_STAGING:
            value: "http://localhost:5001"
          METAPHOR_FRONT_STAGING:
            value: "http://localhost:4001"
          METAPHOR_PROD:
            value: "http://localhost:3002"
          METAPHOR_GO_PROD:
            value: "http://localhost:5002"
          METAPHOR_FRONT_PROD:
            value: "http://localhost:4002"
          KUBEFIRST_VERSION:
            value: "1.10.9"
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
